apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/configuration-snippet: |
        if ($host = 'www.overscroll.com' ) {
          rewrite ^ https://overscroll.com$request_uri permanent;
        }
      
    name: echo-ingress
    namespace: default
  spec:
    rules:
    - host: echo1.kube.overscroll.com
      http:
        paths:
        - backend:
            serviceName: echo1
            servicePort: 80
    - host: echo2.kube.overscroll.com
      http:
        paths:
        - backend:
            serviceName: echo2
            servicePort: 80
    - host: api.overscroll.com
      http:
        paths:
        - backend:
            serviceName: strapi
            servicePort: 80
    - host: overscroll.com
      http:
        paths:
        - backend:
            serviceName: website
            servicePort: 80
    tls:
    - hosts:
      - echo1.kube.overscroll.com
      - echo2.kube.overscroll.com
      - api.overscroll.com
      - overscroll.com
      secretName: letsencrypt-prod
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""